### PR TITLE
add preliminary support for animate.css, clean up HTML example

### PR DESCRIPTION
**Pull request by theonesean**
this is a cool idea, i added animate.css (i gotta look at the jQuery for making individual elements animate but it seems v possible) and it preliminarily works

### CODE REVIEW

**Comment by theonesean** [comment]
i'd also like to write a markdown converter for slides, seems like it'd be p simple

**Comment by JarrettBillingsley** [comment]
btw this is HTML5 and not XHTML, the <br/> syntax is technically invalid

**Comment by theonesean** [comment]
oshit, lemme change that and re-req

**Comment by theonesean** [comment]
there we go

**Pull request merged**
